"""add_quality_score_to_reviews

Revision ID: ab1542bb77d3
Revises: 6735577a0f5c
Create Date: 2026-07-09 00:13:44.763690

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab1542bb77d3"
down_revision: str | None = "6735577a0f5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("quality_score", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "quality_score")
    # ### end Alembic commands ###
