"""add line numbers to findings

Revision ID: ba71de0968ea
Revises: 53f0fd836c00
Create Date: 2026-07-06 15:23:23.856126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ba71de0968ea'
down_revision: Union[str, None] = '53f0fd836c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('line_start', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('line_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'line_end')
    op.drop_column('findings', 'line_start')
    # ### end Alembic commands ###
